var apartments = [
    {id: 1, title: 'My cool apartment', description: 'My apartment description', cityId: 2, owner: 1, price: 30, main_image: "apartments/apartment_1.jpg", images: ["apartments/apartment_1.jpg","apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '330 3rd Ave', sqft: 7500, status: 1, for_rent: false,for_sale: true}, 
    {id: 2, title: 'My nice apartment', description: 'My nice apartment description', cityId: 6, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: '330 3rd Ave', main_image: "apartments/apartment_2.jpg", images: ["apartments/apartment_6.jpg", "apartments/apartment_7.jpg", "apartments/apartment_8.jpg", "apartments/apartment_9.jpg", "apartments/apartment_10.jpg"], for_rent: false, for_sale: false},
    {id: 3, name: 'My cool apartment', title: 'My cool apartment', description: 'My apartment description', cityId: 17, owner: 1, price: 30, main_image: "apartments/apartment_3.jpg", images: ["apartments/apartment_10.jpg", "apartments/apartment_11.jpg", "apartments/apartment_12.jpg", "apartments/apartment_13.jpg","apartments/apartment_14.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true,for_sale: false},
    {id: 4, name: 'My nice apartment', title: 'My nice apartment', description: 'My nice apartment description', cityId: 13, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Saloona 23 st', main_image: "apartments/apartment_4.jpg", images: ["apartments/apartment_15.jpg", "apartments/apartment_16.jpg", "apartments/apartment_17.jpg", "apartments/apartment_18.jpg", "apartments/apartment_19.jpg"], for_rent: false, for_sale: true},
    {id: 5, title: 'My cool apartment', description: 'My apartment description', cityId: 4, owner: 1, price: 30, main_image: "apartments/apartment_4.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg","apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Rozeni 423 st', sqft: 7500, status: 1, for_rent: false,for_sale: false},
    {id: 6, title: 'My nice apartment', description: 'My nice apartment description', cityId: 2, owner: 2, price: 1000, number_of_beds: 3, number_of_rooms: 4, address: 'Zurik 52 st', main_image: "apartments/apartment_5.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], for_rent: true, for_sale: false}, 
    {id: 7, title: 'My cool apartment', description: 'My apartment description', cityId: 15, owner: 1, price: 1000, main_image: "apartments/apartment_6.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Korab 41 st', sqft: 7500, status: 1, for_rent: false,for_sale: false},
    {id: 8, title: 'My nice apartment', description: 'My nice apartment description', cityId: 21, owner: 2, price: 1000, number_of_beds: 3, number_of_rooms: 4, address: 'Moris 422 st 33s', main_image: "apartments/apartment_7.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], for_rent: false, for_sale: false},
    {id: 9, title: 'My cool apartment', description: 'My apartment description', cityId: 16, owner: 1, price: 30, main_image: "apartments/apartment_8.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: false, for_sale: false},
    {id: 10, title: 'My nice apartment', description: 'My nice apartment description', cityId: 12, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "apartments/apartment_9.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg","apartments/apartment_4.jpg" ,"apartments/apartment_4.jpg"], for_rent: true, for_sale: true},
    {id: 11, title: 'My cool apartment', description: 'My apartment description', cityId: 20, owner: 1, price: 30, main_image: "apartments/apartment_10.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: true},
    {id: 12, title: 'My nice apartment', description: 'My nice apartment description', cityId: 7, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "apartments/apartment_11.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], for_rent: false, for_sale: false},
    {id: 13, title: 'My cool apartment', description: 'My apartment description', cityId: 8, owner: 1, price: 30, main_image: "apartments/apartment_12.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 14, title: 'My nice apartment', description: 'My nice apartment description', cityId: 9, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "apartments/apartment_13.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg","apartments/apartment_4.jpg"], for_rent: true, for_sale: false},
    {id: 15, title: 'My cool apartment', description: 'My apartment description', cityId: 9, owner: 1, price: 30, main_image: "apartments/apartment_14.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 1, for_rent: true, for_sale: false},
    {id: 16, title: 'My nice apartment', description: 'My nice apartment description', cityId: 10, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "apartments/apartment_15.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], for_rent: true, for_sale: false},
    {id: 17, title: 'My cool apartment', description: 'My apartment description', cityId: 19, owner: 1, price: 30, main_image: "apartments/apartment_16.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 1, for_rent: true, for_sale: false},
    {id: 18, title: 'My nice apartment', description: 'My nice apartment description', cityId: 5, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "apartments/apartment_17.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], for_rent: true, for_sale: false},
    {id: 19, title: 'My cool apartment', description: 'My apartment description', cityId: 6, owner: 1, price: 30, main_image: "apartments/apartment_18.jpg", images: ["apartments/apartment_1.jpg", "apartments/apartment_2.jpg", "apartments/apartment_3.jpg", "apartments/apartment_4.jpg", "apartments/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 1, for_rent: true, for_sale: false},
    {id: 20, title: 'My nice apartment', description: 'My nice apartment description', cityId: 2, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "apartments/apartment_19.jpg", images: ["apartments/apartment_8.jpg", "apartments/apartment_21.jpg", "apartments/apartment_14.jpg", "apartments/apartment_4.jpg", "apartments/apartment_7.jpg"], for_rent: true, for_sale: false
}];
export {apartments};